'use client';

import React from 'react';
import { X, Printer, ShieldAlert, FileText, Calendar, CheckCircle2, AlertTriangle, Target } from 'lucide-react';
import { DiagnosticResult, DISEASE_MAP } from '../types';

interface ScreeningSummaryModalProps {
  isOpen: boolean;
  onClose: () => void;
  result: DiagnosticResult;
}

export default function ScreeningSummaryModal({ isOpen, onClose, result }: ScreeningSummaryModalProps) {
  if (!isOpen) return null;

  const disease = DISEASE_MAP[result.prediction.toLowerCase()] || {
    code: result.prediction,
    friendlyName: result.prediction,
    clinicalName: result.prediction,
    urgency: 'routine',
    type: 'benign',
    whatIsIt: 'Automated AI classification result.',
    recommendedNextStep: 'Consult a dermatologist for confirmation.',
    categoryBadge: 'Detected Condition',
  };

  const confidencePercent = Math.round(result.confidence_score * 100);
  const formattedDate = new Date(result.created_at).toLocaleString('en-US', {
    dateStyle: 'full',
    timeStyle: 'short'
  });

  const fullImageUrl = result.image_url.startsWith('http')
    ? result.image_url
    : `http://localhost:8000${result.image_url}`;

  const classOrder = ['mel', 'bcc', 'akiec', 'nv', 'bkl', 'df', 'vasc'];

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 sm:p-6 bg-black/60 backdrop-blur-xs overflow-y-auto animate-in fade-in duration-200">
      {/* Backdrop click */}
      <div className="fixed inset-0" onClick={onClose}></div>

      {/* Modal Dialog Card */}
      <div className="relative w-full max-w-2xl bg-white dark:bg-slate-900 rounded-3xl shadow-2xl border border-slate-200 dark:border-slate-800 z-10 overflow-hidden flex flex-col max-h-[90vh] my-auto">
        {/* Modal Toolbar (hidden during print) */}
        <div className="p-4 sm:p-5 border-b border-slate-200 dark:border-slate-800 flex items-center justify-between bg-slate-50 dark:bg-slate-800/80 print:hidden">
          <div className="flex items-center gap-2">
            <FileText className="w-5 h-5 text-cyan-600 dark:text-cyan-400" />
            <h3 className="text-base font-bold text-slate-900 dark:text-white">
              AI Screening Summary (Printable)
            </h3>
          </div>

          <div className="flex items-center gap-2">
            <button
              type="button"
              onClick={handlePrint}
              className="inline-flex items-center gap-1.5 px-3.5 py-1.5 rounded-xl bg-cyan-500 hover:bg-cyan-600 text-white text-xs font-bold transition-all active:scale-95 shadow-xs"
            >
              <Printer className="w-3.5 h-3.5" />
              <span>Print / Save as PDF</span>
            </button>

            <button
              type="button"
              onClick={onClose}
              className="p-1.5 rounded-xl text-slate-400 hover:text-slate-900 dark:hover:text-white transition-colors"
            >
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* Printable Document Content */}
        <div className="p-6 sm:p-8 overflow-y-auto space-y-6 text-slate-900 dark:text-slate-100 print:text-black print:bg-white print:p-0">
          {/* TOP-OF-DOCUMENT MANDATORY NON-CLINICAL DISCLAIMER */}
          <div className="p-4 rounded-2xl bg-amber-50 border-2 border-amber-300 text-amber-950 text-xs leading-relaxed flex items-start gap-3">
            <ShieldAlert className="w-6 h-6 text-amber-600 flex-shrink-0 mt-0.5" />
            <div>
              <strong className="block text-sm font-bold text-amber-900 mb-1">
                NON-CLINICAL AI SCREENING SUMMARY — NOT A MEDICAL DIAGNOSIS
              </strong>
              <p>
                This summary is generated by an automated convolutional neural network ensemble for research and early self-examination assistance. It has NOT been reviewed, verified, or confirmed by a licensed pathologist or dermatologist. Do NOT use this document as a substitute for professional medical advice, clinical diagnosis, or treatment. Always consult a certified healthcare professional.
              </p>
            </div>
          </div>

          {/* Document Header */}
          <div className="flex items-start justify-between border-b border-slate-200 dark:border-slate-800 pb-4">
            <div>
              <div className="flex items-center gap-2 mb-1">
                <div className="w-6 h-6 rounded-lg bg-cyan-500 text-white flex items-center justify-center text-xs font-bold">
                  <Target className="w-3.5 h-3.5" />
                </div>
                <h1 className="text-xl font-black tracking-tight text-slate-900 dark:text-white print:text-black">
                  DermAI Screening Summary
                </h1>
              </div>
              <p className="text-xs text-slate-500">HAM10000 7-Class Deep Learning Ensemble</p>
            </div>

            <div className="text-right text-xs text-slate-500">
              <p className="font-bold text-slate-800 dark:text-slate-200 print:text-black">Scan ID: #{result.id}</p>
              <p>{formattedDate}</p>
            </div>
          </div>

          {/* Primary Result & Scan Image */}
          <div className="grid sm:grid-cols-3 gap-5 items-start">
            <div className="sm:col-span-1 rounded-2xl border border-slate-200 dark:border-slate-700 overflow-hidden bg-slate-100 dark:bg-slate-800 p-2">
              <img
                src={fullImageUrl}
                alt="Analyzed Skin Scan"
                className="w-full h-40 object-contain rounded-xl"
              />
              <p className="text-[10px] text-center text-slate-400 mt-1.5 font-medium">Submitted Scan Photo</p>
            </div>

            <div className="sm:col-span-2 space-y-3">
              <div>
                <span className="text-[11px] font-bold uppercase tracking-wider text-slate-400">Primary AI Pattern Match</span>
                <h2 className="text-2xl font-black text-slate-900 dark:text-white print:text-black">
                  {disease.friendlyName}
                </h2>
                <p className="text-xs text-slate-600 dark:text-slate-300">
                  Medical Category: <strong>{disease.clinicalName} ({disease.code})</strong>
                </p>
              </div>

              <div className="p-3 bg-slate-50 dark:bg-slate-800/60 rounded-xl border border-slate-200/80 dark:border-slate-800 text-xs">
                <span className="text-slate-500 font-medium">AI Certainty Level:</span>{' '}
                <strong className="text-slate-900 dark:text-white print:text-black text-sm font-mono">{confidencePercent}%</strong>
                <p className="text-[11px] text-slate-500 mt-0.5">
                  {confidencePercent >= 70 ? 'High certainty model pattern match' : 'Low certainty (in-person review strongly advised)'}
                </p>
              </div>

              <div className="text-xs text-slate-600 dark:text-slate-300 space-y-1">
                <p><strong>What is it:</strong> {disease.whatIsIt || disease.simpleExplanation}</p>
                <p><strong>Next Step:</strong> {disease.recommendedNextStep || disease.recommendedAction}</p>
              </div>
            </div>
          </div>

          {/* Full 7-Class Probability Table */}
          <div>
            <h3 className="text-xs font-bold text-slate-800 dark:text-slate-200 uppercase tracking-wider mb-2 print:text-black">
              Full 7-Class Softmax Probability Distribution
            </h3>
            <div className="border border-slate-200 dark:border-slate-800 rounded-xl overflow-hidden text-xs">
              <table className="w-full text-left">
                <thead className="bg-slate-50 dark:bg-slate-800 text-slate-600 dark:text-slate-300 text-[11px] font-bold uppercase">
                  <tr>
                    <th className="p-2.5">Condition</th>
                    <th className="p-2.5">Code</th>
                    <th className="p-2.5">Risk Tier</th>
                    <th className="p-2.5 text-right">Probability</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-100 dark:divide-slate-800">
                  {classOrder.map((code) => {
                    const item = DISEASE_MAP[code];
                    let prob = 0;
                    if (result.probabilities && typeof result.probabilities[code] === 'number') {
                      prob = result.probabilities[code];
                    } else if (result.prediction.toLowerCase() === code) {
                      prob = result.confidence_score;
                    }
                    const isTop = result.prediction.toLowerCase() === code;

                    return (
                      <tr key={code} className={isTop ? 'bg-cyan-50/50 dark:bg-cyan-950/30 font-bold' : ''}>
                        <td className="p-2.5">{item.friendlyName}</td>
                        <td className="p-2.5 font-mono uppercase text-slate-500">{code}</td>
                        <td className="p-2.5 uppercase text-[10px]">{item.type}</td>
                        <td className="p-2.5 text-right font-mono">{Math.round(prob * 100)}%</td>
                      </tr>
                    );
                  })}
                </tbody>
              </table>
            </div>
          </div>

          {/* End of Report Signature & Timestamp */}
          <div className="pt-4 border-t border-slate-200 dark:border-slate-800 text-[11px] text-slate-400 flex items-center justify-between print:text-slate-600">
            <span>DermAI Local AI Engine</span>
            <span>Generated on {formattedDate}</span>
          </div>
        </div>
      </div>
    </div>
  );
}
