"""test batch mode

Revision ID: 78b0ba079a1f
Revises: f49dc2a78de2
Create Date: 2026-08-21 10:16:20.132048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78b0ba079a1f'
down_revision: Union[str, None] = 'f49dc2a78de2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diagnosis_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test_column', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diagnosis_results', schema=None) as batch_op:
        batch_op.drop_column('test_column')

    # ### end Alembic commands ###
