"""Initial migration

Revision ID: f49dc2a78de2
Revises: 
Create Date: 2026-08-20 15:58:26.307238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f49dc2a78de2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diagnosis_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cancer_type', sa.String(), nullable=False),
    sa.Column('image_filename', sa.String(), nullable=False),
    sa.Column('image_path', sa.String(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('prediction', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diagnosis_results_cancer_type'), 'diagnosis_results', ['cancer_type'], unique=False)
    op.create_index(op.f('ix_diagnosis_results_id'), 'diagnosis_results', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_diagnosis_results_id'), table_name='diagnosis_results')
    op.drop_index(op.f('ix_diagnosis_results_cancer_type'), table_name='diagnosis_results')
    op.drop_table('diagnosis_results')
    # ### end Alembic commands ###
